# overrides for local development
version: '3'
volumes: 
  pgdata:
services:
  api:
    # this starts up nodemon so it dynamically takes in changes
    entrypoint: ["npm", "run", "dev"]
    volumes:
      # This will mount in your source code into the image
      - .:/app
  ## local database for testing
  db:
    image: postgres:11.1
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: devuser
      POSTGRES_DB: testapp
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - 5432
